name: Test Deployment
run-name: Deploying a website 🚀
on: [push]
jobs:
  Test-Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: '/'
        destination-username: 'kkolago'
        destination-repository: 'sens-box-website'
        destination-directory: 'public'
        commit-email: 'krzysztof.kolago@gmail.com'
